version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  buildImage:
    machine: true     
   
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run: docker build -t dmaxim/barney:v3.1 -f src/circle-Dockerfile .

      - run: docker push dmaxim/barney:v3.1
    
  test:
    executor: win/default
    
    steps:
      - checkout
      - run: dotnet test src/Barney.Tests.Unit/Barney.Tests.Unit.csproj
  
  deploy:
    machine: true

    steps:
      - run: echo deploy step


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - buildImage:
          requires:
            - test
      - deploy:
          requires:
            - buildImage
