apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: barney-web
spec:
  type: 0
  ResourceId: /subscriptions/bb0c99b7-d44d-413a-b294-564466712637/resourcegroups/rg-mxinfo-kube/providers/Microsoft.ManagedIdentity/userAssignedIdentities/barney-webui
  ClientID: 516c66be-63a2-4f64-add3-8493c096ecff
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: barney-web-identity-binding
spec:
  AzureIdentity: barney-web
  Selector: barney-web
