apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: barney-web
spec:
  dnsNames:
  - barney.danmaxim.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tls-secret-barney-web
